athena_allowed_datatypes = [
    "BINARY",
    "BIGINT",
    "BOOLEAN",
    "CHAR",
    "DATE",
    "DECIMAL",
    "DOUBLE",
    "INT",
    "INTEGER",
    "INTERVAL",
    "REAL",
    "SMALLINT",
    "STRING",
    "TIME",
    "TIME WITH TIME ZONE",
    "TIMESTAMP",
    "TIMESTAMP WITH TIME ZONE",
    "TINYINT",
    "VARCHAR",
]

# invalid Athena datatypes: Athena equivalents
common_datatype_conversions = {
    "FLOAT": "DOUBLE",
    "TEXT": "STRING",
    "NVARCHAR": "VARCHAR",
    "CHARACTER VARYING": "VARCHAR",
    "CHARACTER": "CHAR",
    "NUMERIC": "DECIMAL",
    "DEC": "DECIMAL",
    "SMALLSERIAL": "SMALLINT",
    "SERIAL": "INTEGER",
    "BIGSERIAL": "BIGINT",
    "DATETIME": "TIMESTAMP",
    "DATETIME2": "TIMESTAMP",
    "TIMESTAMP WITHOUT TIME ZONE": "TIMESTAMP",
    "TIMESTAMP WITH TIME ZONE": "TIMESTAMP WITH TIME ZONE",
    "BOOL": "BOOLEAN",
    "BIT": "BOOLEAN",
    "VARBINARY": "BINARY",
}
