allowed_athena_functions = [
    # Type conversion
    "cast",
    "try_cast",
    "typeof",
    # Control flow and null handling
    "if",
    "case",
    "nullif",
    "is_null",
    "is_not_null",
    "try",
    # Bitwise
    "bitwise_and",
    "bitwise_or",
    "bitwise_xor",
    "bitwise_not",
    "bit_count",
    "bitwise_shift_left",
    "bitwise_shift_right",
    # Logical helpers / pseudo-functions
    "in",
    "like",
    # String
    "ascii",
    "bit_length",
    "btrim",
    "char",
    "concat",
    "contains",
    "ends_with",
    "fields",
    "format",
    "from_utf8",
    "initcap",
    "length",
    "lower",
    "lpad",
    "ltrim",
    "regexp_extract",
    "regexp_replace",
    "replace",
    "rpad",
    "rtrim",
    "split",
    "split_part",
    "strpos",
    "substr",
    "substring",
    "to_base64",
    "trim",
    "upper",
    "uuid",
    # Date and time
    "current_date",
    "current_time",
    "current_timestamp",
    "date",
    "date_add",
    "date_diff",
    "date_format",
    "date_parse",
    "day",
    "day_of_month",
    "day_of_week",
    "day_of_year",
    "hour",
    "minute",
    "month",
    "now",
    "second",
    "timestamp",
    "timestamp_add",
    "timestamp_diff",
    "to_char",
    "to_date",
    "to_iso8601",
    "to_timestamp",
    "year",
    # Math
    "abs",
    "acos",
    "asin",
    "atan",
    "atan2",
    "cbrt",
    "ceiling",
    "ceil",
    "coalesce",
    "cos",
    "cot",
    "degrees",
    "exp",
    "floor",
    "greatest",
    "least",
    "ln",
    "log",
    "log10",
    "mod",
    "pi",
    "power",
    "pow",
    "radians",
    "rand",
    "round",
    "sign",
    "sin",
    "sqrt",
    "tan",
    "truncate",
    # Aggregate
    "avg",
    "count",
    "approx_distinct",
    "sum",
    "min",
    "max",
    "corr",
    "covar_pop",
    "covar_samp",
    "stddev",
    "stddev_pop",
    "stddev_samp",
    "variance",
    "var_pop",
    "var_samp",
    # Array, map and JSON
    "array",
    "array_distinct",
    "array_join",
    "array_length",
    "array_max",
    "array_min",
    "array_position",
    "array_remove",
    "array_reverse",
    "array_sort",
    "array_union",
    "element_at",
    "filter",
    "flatten",
    "json_array_contains",
    "json_array_get",
    "json_array_length",
    "json_array_length_cast_to_bigint",
    "json_format",
    "json_parse",
    "map",
    "reduce",
    "transform",
    "zip",
    # Window (Analytic) functions
    "row_number",
    "rank",
    "dense_rank",
    "ntile",
    "lag",
    "lead",
    "first_value",
    "last_value",
]

# Athena datetime functions that are not called with () on the end
# i.e. we just use CURRENT_DATE not CURRENT_DATE()
athena_datetime_literals = [
    "CURRENT_DATE",
    "CURRENT_TIME",
    "CURRENT_TIMESTAMP",
    "LOCALTIMESTAMP",
]

# functions used in other types of sql -> their athena equivalents
common_function_conversions = {
    "UNIX_TIMESTAMP": "to_unixtimestamp",
    "DATE_FORMAT": "format_datetime",
}
